#!/usr/bin/python
import time, subprocess, re, os
while True:
	try:
		start = time.time()

#		battery = subprocess.check_output(["acpi","-b"])
#		batteryRegex = re.search(r'[^ :]{0,3}([Cc]harging|Full), [0-9]{1,3}%',battery).group(0)
		ostime = subprocess.check_output("date")
		ostimeRegex = re.search(r'[0-9]{2}:[0-9]{2}:[0-9]{2}',ostime).group(0)
		os.system("xsetroot"+" -name "+"'"+ostimeRegex+"'")
		end = time.time()

		time.sleep(1-(end-start))
	except:
		pass
